# Generated by Django 5.2.9 on 2026-01-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
        ('product', '0011_alter_vendorproducts_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='vendor_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='product.vendorproducts'),
        ),
    ]
