# Generated by Django 5.0.2 on 2025-12-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
