# Generated by Django 5.0.2 on 2025-12-16 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendors_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='vendors.vendors'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
