# Generated by Django 5.0.2 on 2025-12-16 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_bank_vendor_alter_vendors_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='vendors.vendors'),
        ),
    ]
