# Generated by Django 5.2.9 on 2025-12-18 12:43

from django.db import migrations


class Migration(migrations.Migration):
    
    def assign_default_category(apps, schema_editor):
        Product = apps.get_model("product", "Products")
        Category = apps.get_model("category", "Category")

        category, _ = Category.objects.get_or_create(name="Uncategorized")

        Product.objects.filter(category__isnull=True).update(category=category)

    dependencies = [
        ('product', '0002_alter_products_category'),
    ]

    operations = [
        migrations.RunPython(assign_default_category),
    ]

