# Generated by Django 5.2.9 on 2026-01-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_alter_billitem_vendor_product'),
        ('product', '0011_alter_vendorproducts_vendor'),
        ('productReturn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreturn',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='productreturn',
            name='bill_item',
        ),
        migrations.RemoveField(
            model_name='productreturn',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='productreturn',
            name='return_reference',
        ),
        migrations.RemoveField(
            model_name='productreturn',
            name='return_type',
        ),
        migrations.AddField(
            model_name='productreturn',
            name='resolved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomerProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_qty', models.PositiveIntegerField()),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('resolution_type', models.SmallIntegerField(blank=True, choices=[(1, 'Refund'), (2, 'Replacement')], null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Resolved'), (3, 'Rejected')], default=1)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_product_returns', to='bill.bill')),
                ('bill_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_product_returns', to='bill.billitem')),
                ('vendor_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_product_returns', to='product.vendorproducts')),
            ],
            options={
                'db_table': 'customer_product_returns',
            },
        ),
    ]
